#!/usr/bin/env python3
"""Build the standalone partner working brief. No live CRM writes or dependencies."""
from pathlib import Path
import html, json

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'static/fund-ii-working-session'
OUT.mkdir(parents=True, exist_ok=True)
def e(v): return html.escape(str(v), quote=True)
def person(name, **kw): return dict(name=name, **kw)
def notion(id): return 'https://app.notion.com/p/' + id

groups = [
 dict(id='more-time', section='returning', title='They want more time with us', short='More time together', read='These LPs are signaling that more time together could be useful.', objective='Build current Fund II conviction through a conversation or experience that addresses what they actually want to understand.', work='Propose the interaction and what it should accomplish. Use a next step they have already suggested when there is one.', align='Agree the right format, substance and partner involvement.', people=[
  person('Ignacio Rosales', context='Gadi includes Ignacio among the returning LPs showing interest in spending more time together.'),
  person('Kim Bertz', context='September 16 group discussion: Kim, speaking for herself and Andy, proposed a deeper Fund II conversation and said they might invite prospective investors once they knew when it would happen. She emphasized learning from other LPs’ questions.', basis='Group discussion · Sep 16', next='Decide the smallest useful shared Fund II discussion, then propose its scope and timing. Establish Kim and Andy’s own investment appetite separately.', nuance='Kim did not offer to organize an event. A shared format is a supported proposal, not an agreed plan or a Fund II commitment.', url=notion('198daeb290268093b358c0d600820074')),
  person('Kurt Read'),
  person('Darren Fredette', context='The July 10 CRM note records that Darren was probably comfortable writing a Fund II check, with an interest in how Fund I returns are framed.', basis='CRM note · Jul 10', next='Identify the remaining investment question and bring the current evidence into a re-up conversation.', nuance='There may already be investment appetite here; more time is useful if it addresses the actual unresolved question.', url=notion('198daeb2902680c68045cb743f8160f8')),
  person('Roberto Viviani')]),
 dict(id='independent', section='returning', title='They may decide on their own conviction', short='Independent re-up decisions', read='Gadi believes these LPs can evaluate Fund II without waiting for external fundraising momentum.', objective='Open direct re-up conversations with a deliberately chosen first group.', work='Choose the first few names, explain why now, and bring an appropriate ask backed by the current Fund II case.', align='Choose where to start and calibrate the ask. Independence is not evidence that someone is already ready to invest.', people=[person(n) for n in ['Marc Fielding','Charles Nelsen','Jonathan Siegel','Michael Bhagat','Keith Guerin','Nico Bistolfi','Justin Alexander','Jonny Price','Casey Melcher','Daniel Correa','Bou Berendsen','Thaloz','Joshua Harvey']]),
 dict(id='momentum', section='returning', title='Momentum or timing may matter', short='Momentum & timing', read='Progress elsewhere may influence these LPs’ confidence or willingness to decide. The dependencies are working hypotheses.', objective='Identify what would help each person decide, and what can move before that condition is met.', work='Distinguish a stated condition from a relationship read. Name the relevant person, evidence or real milestone.', align='Test which dependencies warrant waiting and which permit a conversation now.', people=[
  person('Aayush Phumbhra', context='Gadi’s read, based on observing other decisions: Aayush may respond better when a real milestone gives him a reason to decide. He has not stated a Fund II prerequisite.', basis='Gadi’s read · Oct 1', next='Establish current appetite and consider a later decision point around a real fundraising milestone. Avoid relying on Aayush to create the opening momentum.', nuance='The working hypothesis concerns timing; it does not establish a lack of conviction or a need for more relationship building.', url=notion('198daeb290268078ba40e3b4bd28a978')),
  person('Joao Pedro Vasconcellos'),
  person('Sergio Cantarovici', via='Guido Grinbaum', context='On August 23, Guido reported that Sergio would invest. There is no direct confirmation or amount in the reviewed CRM note.', basis='CRM note · Aug 23', next='Use the relationship and endorsement to establish Sergio’s own current interest and possible amount.', nuance='Guido’s endorsement does not establish that Sergio must wait for Guido to sign.', url=notion('198daeb2902680dba6b6f7cd01419303')),
  person('Matias Colotuzzo', via='Santi Pehar'), person('Bernhard Gapp')]),
 dict(id='returning-intent', section='returning', title='There are indications of a yes', short='Intent to make concrete', read='Gadi’s “kind of soft committed” group. The statements, amounts and conditions differ.', objective='Establish exactly what has been agreed and resolve the remaining amount, timing, condition or paperwork.', work='Bring the latest commitment statement. Keep any proposed increase separate from an existing agreement.', align='Decide where we need a new investment decision and where we should simply progress the one already made.', people=[
  person('Santiago Pehar', context='August 18 meeting note: Santi said he would invest at least twice his $12.5k Fund I check, implying at least $25k. Written commitment mechanics remain open in the reviewed record.', basis='CRM note · Aug 18', next='Confirm the intended amount and progress the written commitment process.', url=notion('198daeb290268000b6e9f88cfc3f7783')),
  person('Alan Descoins', context='August 23 note: Alan confirmed he would invest again. The amount remained open, with $25k, $50k or $100k under discussion.', basis='CRM note · Aug 23', next='Resolve sizing and the next execution step, subject to any newer context.', url=notion('198daeb29026807aa97fce72c1ca2f86')),
  person('Ariel Muslera', context='The August 20 CRM note records at least twice his $25k Fund I investment, with timing tied to a house sale. An increase to $100k was an ask to explore.', basis='CRM note · Aug 20', next='Confirm the current timing and amount; keep the possible increase separate from the existing indication.', url=notion('198daeb2902680e889f0f1919dbad245')),
  person('Matthew Kruger', context='September 17: Matt wanted to participate, with capital returns expected by December. No new amount was confirmed. Gadi’s later preference was to wait for a substantive reason to reconnect.', basis='CRM note · Sep 17 / Gadi’s later read', next='Choose a useful revisit point tied to the actual timing issue. Resolve size when the conversation is ready.', nuance='The earlier $50k base and $100k upside were internal assumptions, not Matt’s commitment.', url=notion('198daeb2902680839493dcb4f08ee081')),
  person('Guido Grinbaum', context='August 23 WhatsApp recap: Guido reconfirmed a $150k Fund II commitment and had endorsed Antigravity to others.', basis='CRM note · Aug 23', next='Progress the existing $150k agreement. Discuss a possible increase separately if appropriate.', url=notion('198daeb2902680008dfcfbc162950531')),
  person('Ariel Arrieta'),
  person('Power Law Capital', context='August 11 note records a $100k commitment and Passthrough paperwork sent; signature remained pending. No wire was due then.', basis='CRM note · Aug 11', next='Establish whether there is an unresolved investment or administrative issue and agree how to complete the process.', nuance='The earlier agenda deferred signing follow-ups until close momentum. Revisit whether that is still the right partner policy; it is not an LP-stated requirement.', url=notion('198daeb290268070b06de263c2d13a18')),
  person('Daniel Jabbour', context='The CRM has a Soft Commit stage and $25k field, but the inspected status and body do not preserve the underlying statement.', basis='CRM record · basis to confirm', next='Recover what was agreed, when, and on what conditions before choosing the follow-up.', url=notion('198daeb2902680628bcbe582a53e112d'))]),
 dict(id='signed', section='returning', title='Reported signed', short='Signed', read='Alan Brande is signed, per Gadi’s October 1 update.', objective='Complete any remaining administration and keep the LP informed.', work='Check the remaining fund-side process and give it an owner.', align='Handle exceptions; signing, acceptance and funding are separate facts.', people=[person('Alan Brande', basis='Gadi’s report · Oct 1', context='Gadi reports that Alan has signed. This working session did not reconcile final admission or payment.', next='Confirm remaining administrator steps and continue appropriate LP communication.')]),
 dict(id='unclassified', section='returning', title='Their place in the approach is still open', short='Still to classify', read='Gadi has not yet settled the best approach to these relationships.', objective='Learn enough about the most relevant names to decide whether and how to pursue them now.', work='Identify the missing context and the simplest way to recover it. Start with the names that could change the first wave.', align='Choose which uncertainties deserve attention now.', people=[person(n) for n in ['Guillermo Rauch','Enzo Cavalie','Andres Perez Soderi','Kevin Novak','Ro Gupta','Susan Liu','Zack Rosen']]),
 dict(id='dormant', section='returning', title='Paused', short='Dormant', read='Salomon Abauat is dormant, per Gadi.', objective='Reopen only if there is a meaningful reason.', work='Preserve why the relationship is paused and identify a real reopening condition, if one exists.', align='Decide whether anything has changed enough to justify attention.', people=[person('Salomon Abauat')]),
 dict(id='declined', section='returning', title='Declined Fund II', short='Declined', read='Juan Saavedra declined Fund II, per Gadi.', objective='Respect the decision and maintain the relationship appropriately.', work='Preserve the reason if known. Revisit only if relevant circumstances change.', align='Keep this outside the active push unless new context warrants a review.', people=[person('Juan Saavedra')]),
 dict(id='new-momentum', section='other', title='New relationships with momentum', short='New momentum', read='Gadi sees current openings worth developing.', objective='Convert the actual investment signal into the next appropriate fund conversation or execution step.', work='Fulfill what was requested or promised. Identify whether the open question is appetite, amount, diligence or documents.', align='Calibrate the next ask to the evidence, not the age of the relationship.', people=[
  person('Joao Vergacas', context='The August CRM notes record interest in writing a check and materials shared. Amount and timing remained open.', basis='CRM notes · Aug 3–8', next='Re-establish current Fund II appetite and resolve the amount or remaining questions.', url=notion('3b2daeb2902681dcbd86fb5b0776d796')),
  person('Doug Chertok', context='September 22: verbal commitment, amount to be determined, and a request for subscription documents. Invite delivery and signature were not confirmed in the reviewed record.', basis='CRM note · Sep 22', next='Confirm the promised invite was delivered and revisit amount within the agreed one-to-two-week window.', url=notion('2fcdaeb2902681b2bb8bd90db795c6ad')),
  person('Arthur Costa', context='He requested Fund II materials when the formal raise began. The separate Halluminate SPV investment provides relationship context; it is not a Fund II commitment.', basis='CRM notes · Aug 31–Sep 5', next='Use the requested materials to open an explicit Fund II discussion.', nuance='Arthur Costa is distinct from Arthur at ONEVC. The CRM’s $1m field is not a confirmed Fund II allocation.', url=notion('3c8daeb29026814c8465efc5e130de79'))]),
 dict(id='old-intent', section='other', title='Older soft commitments to revisit', short='Older intent', read='Earlier intentions have lost momentum, in Gadi’s current assessment.', objective='Establish whether the intention still stands and what would make it actionable now.', work='Bring the original statement and date, then propose a direct but relationship-appropriate reconfirmation.', align='Decide whether the work is reconfirmation, renewed conviction, or an intentional pause.', people=[
  person('Amadeo Pellicce', context='The CRM records a $25k soft commitment associated with a February 17 conversation. Gadi now describes this as older intent that lost momentum.', basis='CRM note · Feb 17 / Gadi’s Oct 1 read', next='Reconfirm current interest, size and timing without assuming the old intention is still actionable.', url=notion('30bdaeb290268120baddc5c611a8ed64')),
  person('Carlos Costa', context='The CRM records a $100k personal soft commitment. Gadi now describes lost momentum. The personal investment is separate from any institutional Valor opportunity.', basis='CRM record / Gadi’s Oct 1 read', next='Establish whether the personal intention still stands and what needs to happen next.', url=notion('2f4daeb29026810d87b7e0ed1ec78ba9'))]),
 dict(id='onboarding', section='other', title='A recent yes, with onboarding unanswered', short='Onboarding unanswered', read='Florian verbally committed recently, but is not responding to Passthrough onboarding, per Gadi.', objective='Resolve what is preventing the agreed investment from progressing.', work='Choose a useful personal follow-up that can surface an administrative issue, timing, an unanswered question or changed intent.', align='Set an appropriate approach and reassessment point. Silence alone does not tell us the cause.', people=[person('Florian Hagenbuch', context='Gadi reports a recent verbal yes and no response to onboarding. The reviewed CRM carries $50k, with a September 8 Passthrough/amount question awaiting a reply.', basis='Gadi’s Oct 1 report / CRM note · Sep 8', next='Agree whether and how to reopen the investment directly, and identify what is blocking progress.', nuance='An earlier agenda proposed waiting for a meaningful reason. The next approach remains a partner decision.', url=notion('2f0daeb2902680489c18f78a2ab41a8a'))]),
 dict(id='vcs', section='other', title='Other VCs with momentum', short='VC relationships', read='These relationships deserve attention, but they involve different people, vehicles and decisions.', objective='Establish the actual investment path and keep useful collaboration distinct from capital.', work='Identify who invests and decides, what is unresolved, and the purpose of each upcoming conversation.', align='Resolve consequential partnership choices together and give each partner a useful role.', people=[
  person('Ryan Bloomer', context='Gadi’s October 1 reassessment prioritizes Ryan’s personal participation and possibly his partners. The institutional Actions opportunity has no current momentum.', basis='Gadi’s assessment · Oct 1', next='Pursue Ryan’s personal decision and explore partner participation; reconfirm size and timing.', nuance='Keep the Actions institutional opportunity separate. An old amount field does not confirm today’s allocation.', url=notion('2f8daeb29026810ea3fafe55f8f819dc')),
  person('Carla Barone', context='The CRM records a $10k personal soft commitment and onboarding sent July 28, alongside active collaboration and introductions.', basis='CRM note · Jul 28 / ongoing context', next='Keep Carla’s personal completion step separate from the ONEVC firm conversation; agree appropriate timing for it.', url=notion('338daeb29026816ab6b8fe57b27465cf')),
  person('ONEVC / Arthur', via='Next week, per Gadi', context='Gadi expects a conversation with Arthur next week. The reviewed ONEVC notes describe unresolved firm allocation and timing; no amount is confirmed.', basis='Gadi’s Oct 1 report / September CRM notes', next='Prepare the meeting to clarify the investing vehicle, feasible allocation and next decision.', nuance='Carla’s personal check is separate. Arthur here is not Arthur Costa.', url=notion('3dddaeb2902681c8b240ecff0b9303a6')),
  person('Base10', context='September 29 note: Rexhi would consult partners about a meaningful Fund II check and possible broader structures. No amount is confirmed.', basis='Meeting note · Sep 29', next='Resolve investment appetite and sizing while agreeing internally how to handle broader partnership scope.', nuance='Keep Base10’s institutional investment, Ade’s personal relationship and Puentes collaboration distinct.', url=notion('3ebdaeb290268157b90df9f061291f40')),
  person('Long Journey Ventures', context='The September 23 note records a deck-feedback conversation with Lee and Jonathan for October 2 at 11 a.m. PT. Fund investments are limited/noncore; no amount or investment timeline was established.', basis='Meeting note · Sep 23', next='Use the planned conversation to establish whether an LP path is realistic this cycle and what concrete help may be available.', nuance='Meeting timing comes from the note and was not rechecked against Calendar for this page.', url=notion('365daeb290268159a1a9fea766c785f1'))])
]

for g in groups:
 for i,p in enumerate(g['people']):
  p['id'] = g['id'] + '-' + str(i+1)
  p.setdefault('basis', 'Gadi’s working map · Oct 1')
  p.setdefault('context', 'Included in this group by Gadi. The latest individual exchange has not been rechecked for this page.')
  p.setdefault('next', g['work'])
  p['group'] = g['short']
people = [p for g in groups for p in g['people']]

def render_person(p):
 via=f'<span class="via">{e(p["via"])}</span>' if p.get('via') else ''
 nuance=f'<p class="nuance">{e(p["nuance"])}</p>' if p.get('nuance') else ''
 url=f'<a class="source-link" href="{e(p["url"])}" target="_blank" rel="noopener noreferrer">Open CRM record ↗</a>' if p.get('url') else ''
 return f'''<div class="person" id="{p['id']}" data-search="{e(p['name']+' '+p.get('via',''))}"><details><summary><span class="person-name">{e(p['name'])}{via}</span><span class="person-indicator">Context <span aria-hidden="true">+</span></span></summary><div class="person-body"><span class="eyebrow">{e(p['basis'])}</span><p>{e(p['context'])}</p><div class="next-step"><span class="small-label">Proposed next work</span><p>{e(p['next'])}</p></div>{nuance}{url}</div></details><label class="pick" title="Add {e(p['name'])} to the first pass"><input type="checkbox" data-pick="{p['id']}" aria-label="Add {e(p['name'])} to first pass"><span class="pick-mark" aria-hidden="true">+</span></label></div>'''

def render_group(g, i):
 return f'''<article class="bucket" id="{g['id']}" data-group="{g['id']}"><header class="bucket-head"><span class="bucket-index">{i:02}</span><div><p class="eyebrow">{e(g['short'])} <span class="count">{len(g['people'])}</span></p><h3>{e(g['title'])}</h3></div></header><p class="bucket-read">{e(g['read'])}</p><div class="bucket-purpose"><span class="small-label">What the work should accomplish</span><p>{e(g['objective'])}</p></div><div class="people">{''.join(render_person(p) for p in g['people'])}</div><details class="approach"><summary>Approach to discuss <span aria-hidden="true">↗</span></summary><div><p><strong>Gadi’s preparation.</strong> {e(g['work'])}</p><p><strong>Agree together.</strong> {e(g['align'])}</p></div></details></article>'''

nav=[('purpose','The purpose'),('returning','Returning LPs'),('other','Other active relationships'),('sequence','What comes first'),('decisions','Our first pass'),('sources','Sources & scope')]
navhtml=''.join(f'<a href="#{id}"><span>{i:02}</span>{title}</a>' for i,(id,title) in enumerate(nav,1))
options=''.join(f'<option value="{id}">{title}</option>' for id,title in nav)
buckets=''.join(f'<a href="#{g["id"]}" data-group-link="{g["id"]}">{e(g["short"])} <span>{len(g["people"])}</span></a>' for g in groups)
returning=''.join(render_group(g,i) for i,g in enumerate(groups,1) if g['section']=='returning')
other=''.join(render_group(g,i) for i,g in enumerate(groups,1) if g['section']=='other')
serialized=json.dumps(people,ensure_ascii=False).replace('</','<\\/')
page=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><meta name="referrer" content="no-referrer"><meta name="description" content="Antigravity Fund II — a working session for Gadi and Daniel."><title>Fund II — The next conversations</title><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%231d3638'/%3E%3Ctext x='32' y='46' font-size='47' text-anchor='middle' fill='%23f5f2e9' font-family='Georgia'%3Ea%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="style.css"></head>
<body><a class="skip" href="#main">Skip to the working brief</a><div class="topbar"><a class="brand" href="#top">antigravity<span> / Fund II</span></a><div class="topmeta"><span class="unlisted">Unlisted working brief</span><span>01 October 2026</span><button type="button" id="print">Print / PDF</button></div><div id="progress"></div></div>
<header class="hero" id="top"><div class="hero-inner"><div><p class="eyebrow">Gadi + Daniel / Partner working session</p><h1>The next<br><em>conversations.</em></h1><p class="hero-deck">A relationship map, an approach for each group,<br class="desktop"> and a deliberate first pass at Fund II.</p><a class="hero-link" href="#returning">Go through the relationships <span>↓</span></a></div><div class="hero-note"><span class="eyebrow">The work ahead</span><p>What’s missing between <br>this relationship <br>and an investment?</p><div class="hero-path"><span>Build conviction</span><span>Ask for a decision</span><span>Follow through</span></div><p class="hero-caption">Different next steps. One fundraising purpose.</p></div></div><div class="hero-bottom"><span>A starting point for discussion</span><span>Context → approach → sequence</span></div></header>
<div class="layout"><aside class="sidebar"><p class="eyebrow">In this session</p><nav aria-label="Chapters">{navhtml}</nav><div class="sidebar-note">The groups are Gadi’s current read. The first pass and schedule are ours to agree.</div><a class="queue-link" href="#decisions">First pass <span data-selected-count>0</span> <span aria-hidden="true">↗</span></a></aside><main id="main"><div class="mobile-nav"><label for="jump">Jump to</label><select id="jump">{options}</select></div>
<section id="purpose" class="chapter"><div class="section-heading"><span>01</span><h2>A clear purpose.<br>An appropriate ask.</h2></div><p class="lead">The goal is to raise Fund II. This session is about choosing whom we pursue first, what each conversation should accomplish, and how progress with one group can strengthen the next.</p><div class="principles"><div><span class="small-label">Context</span><h3>What is missing?</h3><p>Conviction, current appetite, an amount, timing, a condition, or unfinished paperwork.</p></div><div><span class="small-label">Approach</span><h3>What should we propose?</h3><p>A direct investment ask where it fits. A useful intermediate conversation or experience where it helps.</p></div><div><span class="small-label">Sequence</span><h3>Why this person now?</h3><p>A reason to start, a real dependency to resolve, or a deliberate reason to wait.</p></div></div><div class="working-rule"><p>“Here’s what I think is missing, why I think that, and what I’d do next.”</p><span>Gadi brings relationship context and an initial view. We test the approach, choose priorities and divide the work together.</span></div><p class="small">The map below preserves Gadi’s October 1 groupings. They can overlap; they are not CRM stages or a forecast. Expand a name for available context. Add names to the first pass as we decide where to focus.</p></section>
<div class="map-tools"><div><label for="search">Find a relationship</label><input id="search" type="search" placeholder="Name, firm or connection…" autocomplete="off"></div><p id="search-status" aria-live="polite">All relationships in Gadi’s map</p><button id="clear-search" type="button" hidden>Clear search</button></div>
<section id="returning" class="chapter relationship-section"><div class="section-heading"><span>02</span><h2>Start with the people<br>who already know us.</h2></div><p class="lead">Our Fund I LP base contains several different kinds of work. The grouping is a starting hypothesis; the remaining investment question determines the approach.</p><div class="bucket-nav" aria-label="Relationship groups">{''.join(f'<a href="#{g["id"]}">{e(g["short"])} <span>{len(g["people"])}</span></a>' for g in groups if g['section']=='returning')}</div><div class="buckets">{returning}</div></section>
<section id="other" class="chapter relationship-section"><div class="section-heading"><span>03</span><h2>Keep the other<br>openings moving.</h2></div><p class="lead">New interest, older intentions and VC relationships can progress alongside returning LPs. Each needs a clear read of the investment decision in front of us.</p><div class="buckets">{other}</div><details class="side-thread"><summary>Also from the earlier map: Diego Fleischmann <span aria-hidden="true">+</span></summary><p>Diego was previously identified as a materials-ready reactivation. His omission from the latest list has not been treated as a decision to drop him.</p><p>The August meeting note records a request for materials and a deeper online follow-up. Confirm whether he belongs in this first pass.</p><a href="{notion('3a7daeb29026813c9392d8c5caec3bc3')}" target="_blank" rel="noopener noreferrer">Open CRM record ↗</a></details></section>
<section id="sequence" class="chapter"><div class="section-heading"><span>04</span><h2>Decide what comes first.</h2></div><p class="lead">A proposed starting sequence to test together. We can move several kinds of work at once.</p><div class="sequence-list"><article><span>01</span><div><h3>Follow the clearest openings.</h3><p>People who have said yes, asked for something specific, or already have a conversation approaching. Resolve what remains instead of reopening every question.</p><p class="examples">Examples to consider: Doug · Guido · Kim · Long Journey</p></div></article><article><span>02</span><div><h3>Choose our first independent re-ups.</h3><p>Select a manageable group who can evaluate Fund II on their own conviction. Agree why they come first and what we will ask.</p><p class="examples">Select from the independent returning-LP group.</p></div></article><article><span>03</span><div><h3>Test the supposed dependencies.</h3><p>Aayush may need a reason to decide now. Sergio may respond to Guido’s endorsement. Different hypotheses require different approaches; neither automatically means no conversation yet.</p><p class="examples">Current appetite can be established before a later decision milestone.</p></div></article></div><div class="two-notes"><div><span class="small-label">Relationship work</span><p>Name what additional time would help the LP understand, experience or resolve. With Kim, a shared conversation is a concrete proposal worth deciding on.</p></div><div><span class="small-label">A choice to revisit</span><p>For already committed LPs, is waiting for more closing momentum before progressing signatures still the right policy? Separate our choice from an LP’s actual condition.</p></div></div></section>
<section id="decisions" class="chapter"><div class="section-heading"><span>05</span><h2>Our first pass.</h2></div><p class="lead">Choose the relationships, agree the next work, and give it an owner and a date.</p><div class="session-notice"><span class="save-dot" aria-hidden="true"></span><span id="save-status">Notes and selections save in this browser only. Export them to share or keep a copy.</span></div><div class="empty-state" id="empty-state"><span class="empty-plus">+</span><h3>Start with a few names.</h3><p>Use the + beside any relationship to bring it here.<br>Nothing has been preselected.</p><a href="#returning">Go to the relationship map ↑</a></div><div id="decision-list"></div><div class="session-fields"><label for="session-notes">Decisions from our conversation</label><textarea id="session-notes" rows="5" placeholder="The approach we agree on, dependencies to test, and anything we choose to leave for later…"></textarea><div class="review-row"><label for="review-date">Our next review<input type="date" id="review-date"></label><p>Use internal action and review dates. An LP deadline needs its own agreed basis.</p></div></div><div class="export-row"><button class="button" id="export" type="button">Download session notes ↓</button><button class="text-button" id="copy" type="button">Copy notes</button><span id="export-status" role="status"></span></div><details id="export-preview" class="export-preview" hidden><summary>Session notes as text</summary><label for="export-text" class="small">Select and copy this text if your browser does not support downloads or clipboard access.</label><textarea id="export-text" rows="12" readonly></textarea></details></section>
<section id="sources" class="chapter sources"><div class="section-heading"><span>06</span><h2>The context behind this page.</h2></div><p>Prepared October 1, 2026 from Gadi’s relationship map, the partner discussion, Kim’s group conversation and selected CRM and meeting records. The remaining relationships have not been individually rechecked. Dated notes are historical evidence, even when a CRM record was edited more recently.</p><div class="source-grid"><a href="https://dev.obscurely.org/fund-ii-fundraising-onvbc/#opportunities" target="_blank" rel="noopener noreferrer"><span>01 / Strategy</span>Daniel’s working briefing ↗</a><a href="https://notes.granola.ai/d/4db4da82-c07e-4ca8-97d8-99591582c910" target="_blank" rel="noopener noreferrer"><span>02 / Partner discussion</span>September 30 conversation ↗</a><a href="https://app.notion.com/p/antigravity-room/198daeb2902680a7ac19cea98fe0f919?v=23edaeb290268064af71000cc6403d5e" target="_blank" rel="noopener noreferrer"><span>03 / Operating record</span>LP CRM ↗</a></div><p class="small">Relationship notes distinguish Gadi’s judgment, recorded intent and proposed next work. No pipeline totals or probabilities are inferred. This page and its local notes do not update Notion or send messages. Source links require existing access.</p></section>
<footer><span>Antigravity Capital · Gadi + Daniel · October 2026</span><a href="#top">Back to top ↑</a><p>Unlisted and marked noindex. Anyone with this link can view the page.</p></footer></main></div>
<a class="floating-queue" href="#decisions">First pass <span data-selected-count>0</span> <span aria-hidden="true">↗</span></a><noscript><p class="no-js">The complete relationship map is available above. Enable JavaScript to search, select names and save session notes.</p></noscript><script id="relationship-data" type="application/json">{serialized}</script><script src="session.js" defer></script></body></html>'''
(OUT/'index.html').write_text(page)
print(f'Built {OUT}/index.html: {len(groups)} groups, {len(people)} review entries, plus Diego from the earlier map.')
